/**
 * Human Names - 1000+ entries each for male and female
 */

export const HUMAN_MALE_NAMES = [
  // Classic Medieval
  'Aldric', 'Baldric', 'Cedric', 'Derrick', 'Edmund', 'Fredric', 'Godwin', 'Harold', 'Ivan', 'Jasper',
  'Kendrick', 'Leopold', 'Marcus', 'Nathaniel', 'Oswald', 'Percival', 'Quentin', 'Roland', 'Sebastian', 'Theodore',
  'Ulrich', 'Victor', 'Wilhelm', 'Xavier', 'Yorick', 'Zachary', 'Adrian', 'Bernard', 'Conrad', 'Dominic',
  'Everett', 'Felix', 'Gregory', 'Henry', 'Isaac', 'Julian', 'Kenneth', 'Lawrence', 'Maxwell', 'Nicholas',
  'Oliver', 'Patrick', 'Raymond', 'Samuel', 'Thomas', 'Vincent', 'Walter', 'Alexander', 'Benjamin', 'Charles',
  'Daniel', 'Edward', 'Francis', 'George', 'Harrison', 'James', 'Kevin', 'Leonard', 'Martin', 'Nathan',
  'Oscar', 'Peter', 'Richard', 'Stephen', 'Timothy', 'Vaughn', 'William', 'Andrew', 'Brian', 'Christopher',
  'David', 'Eric', 'Frank', 'Gerald', 'Howard', 'Jonathan', 'Kyle', 'Lewis', 'Michael', 'Neil',
  'Owen', 'Paul', 'Randall', 'Scott', 'Travis', 'Vernon', 'Wayne', 'Albert', 'Barry', 'Calvin',
  'Dennis', 'Eugene', 'Floyd', 'Gordon', 'Hugh', 'Jack', 'Keith', 'Lloyd', 'Morris', 'Norman',
  // Fantasy Variants
  'Alaric', 'Brandis', 'Corwin', 'Darius', 'Eldric', 'Fendrel', 'Gareth', 'Hadrian', 'Isen', 'Jareth',
  'Kaden', 'Lysander', 'Magnus', 'Nolan', 'Orion', 'Phelan', 'Quinn', 'Ronan', 'Sterling', 'Tristan',
  'Uther', 'Valdric', 'Wren', 'Xander', 'York', 'Zephyr', 'Ashford', 'Beckett', 'Callum', 'Drake',
  'Emeric', 'Flynn', 'Griffin', 'Hayes', 'Ingram', 'Jensen', 'Kane', 'Lachlan', 'Merrick', 'Nash',
  'Oakley', 'Pierce', 'Quillan', 'Royce', 'Sawyer', 'Theron', 'Ulric', 'Vance', 'Warren', 'Xylon',
  // Noble Names
  'Alistair', 'Bartholomew', 'Cornelius', 'Desmond', 'Egbert', 'Ferdinand', 'Godfrey', 'Humphrey', 'Ignatius', 'Jasper',
  'Kingston', 'Leander', 'Montgomery', 'Nigel', 'Octavian', 'Phineas', 'Quincy', 'Reginald', 'Sylvester', 'Thaddeus',
  'Uriah', 'Valentine', 'Wilfred', 'Xerxes', 'Yardley', 'Zebulon', 'Archibald', 'Baldwin', 'Cassius', 'Damian',
  'Erasmus', 'Fabian', 'Gideon', 'Horatio', 'Isidore', 'Jasper', 'Kingsley', 'Llewellyn', 'Maximilian', 'Neville',
  'Osric', 'Pemberton', 'Quilliam', 'Roderick', 'Sinclair', 'Terrance', 'Ulysses', 'Valerian', 'Wentworth', 'Ximenes',
  // Common Folk Names
  'Alden', 'Bram', 'Cole', 'Dale', 'Evan', 'Finn', 'Glen', 'Hank', 'Ian', 'Jeb',
  'Kent', 'Lars', 'Miles', 'Ned', 'Otto', 'Penn', 'Rolf', 'Seth', 'Tad', 'Uri',
  'Vern', 'Walt', 'Yost', 'Zeke', 'Abel', 'Boyd', 'Clem', 'Drew', 'Earl', 'Ford',
  'Gus', 'Hal', 'Ike', 'Jake', 'Kip', 'Lon', 'Mack', 'Nate', 'Orv', 'Pip',
  'Rafe', 'Stan', 'Tuck', 'Upton', 'Val', 'Webb', 'Yancy', 'Zack', 'Amos', 'Buck',
  // Regional Variants - Northern
  'Bjorn', 'Gunnar', 'Halvar', 'Ivar', 'Jorgen', 'Knud', 'Leif', 'Magnus', 'Njord', 'Odin',
  'Ragnar', 'Sigurd', 'Torsten', 'Ulf', 'Vidar', 'Wulfric', 'Yngvar', 'Asgeir', 'Bjarni', 'Dagfinn',
  'Einar', 'Fritjof', 'Gorm', 'Hakon', 'Ingvar', 'Jarl', 'Ketil', 'Ludvig', 'Mikkel', 'Nikolaj',
  'Olaf', 'Peder', 'Rune', 'Sten', 'Thorvald', 'Ulrik', 'Viggo', 'Wendel', 'Yngve', 'Arvid',
  'Birger', 'Canute', 'Didrik', 'Egil', 'Frode', 'Geir', 'Helge', 'Iver', 'Jostein', 'Kjell',
  // Regional Variants - Southern/Mediterranean
  'Alessandro', 'Benedetto', 'Carlo', 'Dante', 'Emilio', 'Fabrizio', 'Giovanni', 'Hugo', 'Ignacio', 'Julio',
  'Lorenzo', 'Matteo', 'Nico', 'Orlando', 'Paolo', 'Rafael', 'Salvatore', 'Tomas', 'Umberto', 'Vincenzo',
  'Alfonso', 'Bruno', 'Cesar', 'Diego', 'Enrique', 'Felipe', 'Guillermo', 'Hernando', 'Iago', 'Javier',
  'Leandro', 'Miguel', 'Nestor', 'Octavio', 'Pedro', 'Ramon', 'Santiago', 'Teodoro', 'Vasco', 'Xavier',
  'Antonio', 'Benito', 'Cristobal', 'Domingo', 'Esteban', 'Francisco', 'Gonzalo', 'Hector', 'Inigo', 'Jorge',
  // Regional Variants - Eastern
  'Alexei', 'Boris', 'Casimir', 'Dmitri', 'Emil', 'Fyodor', 'Grigori', 'Henrik', 'Igor', 'Janek',
  'Kazimir', 'Lech', 'Mikhail', 'Nikolai', 'Oleg', 'Pavel', 'Radek', 'Sergei', 'Tadek', 'Viktor',
  'Wojciech', 'Yuri', 'Zoran', 'Andrei', 'Bogdan', 'Cyprian', 'Darek', 'Evgeni', 'Filip', 'Gregor',
  'Ivan', 'Janusz', 'Kirill', 'Leonid', 'Marek', 'Nikita', 'Oskar', 'Piotr', 'Roman', 'Stanislav',
  'Timofei', 'Vadim', 'Waclaw', 'Yarek', 'Zbigniew', 'Anton', 'Bronislav', 'Cezary', 'Dawid', 'Eryk',
  // Regional Variants - Western/Celtic
  'Aidan', 'Brennan', 'Cormac', 'Declan', 'Eamon', 'Finbar', 'Galen', 'Hugh', 'Iona', 'Jarlath',
  'Keegan', 'Liam', 'Murphy', 'Niall', 'Oisin', 'Padraig', 'Quinlan', 'Riordan', 'Seamus', 'Tiernan',
  'Uilliam', 'Vaughan', 'Wynne', 'Aengus', 'Brody', 'Cian', 'Donovan', 'Egan', 'Fergal', 'Grady',
  'Hogan', 'Killian', 'Lorcan', 'Malachy', 'Nolan', 'Oran', 'Phelan', 'Quillan', 'Rowan', 'Sullivan',
  'Teagan', 'Ultan', 'Whelan', 'Aodhan', 'Bran', 'Ciaran', 'Darragh', 'Eoghan', 'Fionn', 'Garvan',
  // Merchant/Trade Names
  'Abelard', 'Bastion', 'Colbert', 'Dryden', 'Eldwin', 'Fletcher', 'Garrison', 'Holden', 'Irvin', 'Jarvis',
  'Keaton', 'Landry', 'Mercer', 'Neville', 'Osmond', 'Palmer', 'Quade', 'Reynard', 'Sheldon', 'Tucker',
  'Udell', 'Vester', 'Whitmore', 'Yeoman', 'Zachery', 'Archer', 'Baxter', 'Cooper', 'Dexter', 'Faulkner',
  'Gardner', 'Harper', 'Jagger', 'Keller', 'Lawson', 'Mason', 'Nelson', 'Parker', 'Quinn', 'Roper',
  'Sawyer', 'Tanner', 'Vernon', 'Walker', 'Wright', 'Aldous', 'Barlow', 'Chandler', 'Draper', 'Fisher',
  // Warrior/Military Names
  'Ajax', 'Brutus', 'Cato', 'Dux', 'Evander', 'Flavius', 'Gallus', 'Hector', 'Ivar', 'Julius',
  'Kratos', 'Leonidas', 'Mars', 'Nero', 'Otho', 'Primus', 'Quintus', 'Rex', 'Scipio', 'Titus',
  'Ultor', 'Vitus', 'Wulfstan', 'Xanthus', 'Aetius', 'Belisarius', 'Claudius', 'Drusus', 'Fabius', 'Gaius',
  'Hannibal', 'Imperius', 'Justinian', 'Kael', 'Lucius', 'Maximus', 'Nerva', 'Otis', 'Pertinax', 'Rufus',
  'Septimus', 'Trajan', 'Varro', 'Castor', 'Damon', 'Evander', 'Ferox', 'Gravis', 'Hadrian', 'Lex',
  // Scholar/Clergy Names
  'Anselm', 'Bede', 'Clement', 'Dominic', 'Erasmus', 'Fortunatus', 'Gratian', 'Hilary', 'Innocent', 'Jerome',
  'Kyril', 'Lanfranc', 'Methodius', 'Nicodemus', 'Origen', 'Paschal', 'Quirinus', 'Remigius', 'Simeon', 'Tertullian',
  'Urban', 'Venantius', 'Winfrid', 'Xystus', 'Zacharias', 'Athanasius', 'Basil', 'Cyril', 'Dunstan', 'Elias',
  'Florian', 'Germanus', 'Honorius', 'Isidore', 'Justus', 'Kilian', 'Lambert', 'Maurus', 'Norbert', 'Osmund',
  'Paulinus', 'Quodvultdeus', 'Rupert', 'Severinus', 'Theobald', 'Ulric', 'Vergilius', 'Wilfred', 'Yvo', 'Zeno',
  // Craftsman Names
  'Ashby', 'Brewster', 'Carver', 'Dyer', 'Forger', 'Glover', 'Hammersmith', 'Inkwell', 'Joiner', 'Keeler',
  'Lorimer', 'Miller', 'Nailer', 'Ostler', 'Potter', 'Quarrier', 'Roper', 'Slater', 'Thatcher', 'Upholder',
  'Vintner', 'Wainwright', 'Yeoman', 'Ashwood', 'Blackwood', 'Copperfield', 'Drystone', 'Elmwood', 'Frostforge', 'Goldsmith',
  'Horncarver', 'Ironside', 'Jewelwright', 'Kettlemaker', 'Leatherwork', 'Masonstone', 'Nailbender', 'Oakwright', 'Pewtersmith', 'Quartzhand',
  'Ropemaker', 'Steelhand', 'Tinsmith', 'Woodward', 'Brasswright', 'Chainmaker', 'Daggersmith', 'Fletcherwood', 'Gemcutter', 'Hammerhand',
  // Nature-Inspired
  'Ash', 'Brook', 'Clay', 'Dale', 'Elm', 'Flint', 'Glen', 'Heath', 'Ivy', 'Jasper',
  'Kestrel', 'Lark', 'Moss', 'North', 'Oak', 'Pike', 'Quail', 'Reed', 'Stone', 'Thorn',
  'Vale', 'Wolf', 'Yarrow', 'Alder', 'Birch', 'Cedar', 'Dune', 'Fen', 'Granite', 'Harbor',
  'Iris', 'Jay', 'Kelp', 'Linden', 'Marsh', 'Nettle', 'Otter', 'Pine', 'Ridge', 'Summit',
  'Tide', 'Umber', 'Vine', 'Willow', 'Basalt', 'Cliff', 'Dell', 'Fern', 'Grove', 'Hill',
  // Virtue Names
  'Able', 'Brave', 'Chance', 'Dare', 'Earnest', 'Faith', 'Grant', 'Honor', 'Justice', 'Kemp',
  'Loyal', 'Merit', 'Noble', 'Order', 'Peace', 'Quest', 'Reason', 'Stalwart', 'True', 'Valor',
  'Ward', 'Zeal', 'Amity', 'Bond', 'Candor', 'Duty', 'Equity', 'Fortune', 'Grace', 'Hardy',
  'Intent', 'Judge', 'Kindred', 'Legacy', 'Mercy', 'Oath', 'Pledge', 'Quiet', 'Resolve', 'Sage',
  'Trust', 'Unity', 'Virtue', 'Will', 'Ardent', 'Bold', 'Constant', 'Diligent', 'Endure', 'Firm',
  // Compound/Hyphenated First Elements
  'Aelfric', 'Beornwulf', 'Cynric', 'Dunstan', 'Ealdred', 'Frithuwulf', 'Godric', 'Heardred', 'Ingeld', 'Kenric',
  'Leofric', 'Merewald', 'Nothelm', 'Ordgar', 'Plegmund', 'Raedwald', 'Sigeberht', 'Torhthelm', 'Widsith', 'Aldhelm',
  'Burgred', 'Ceolwulf', 'Deorwine', 'Ecgberht', 'Forthred', 'Goldwine', 'Hereward', 'Irminric', 'Kinewulf', 'Lindhard',
  'Maelgwn', 'Northeald', 'Osberht', 'Penda', 'Redwald', 'Swithhelm', 'Theodric', 'Wulfhere', 'Aethelred', 'Beorhtric',
  'Ceadda', 'Dudda', 'Eadric', 'Fritheswith', 'Guthrum', 'Hrothgar', 'Ingeld', 'Jaenberht', 'Cenric', 'Leofdaeg',
  // Short/Simple Names
  'Abe', 'Ben', 'Cal', 'Dan', 'Ed', 'Gus', 'Hal', 'Jan', 'Ken', 'Len',
  'Max', 'Ned', 'Pat', 'Ray', 'Sam', 'Ted', 'Van', 'Wil', 'Zac', 'Art',
  'Bob', 'Cob', 'Dob', 'Ebb', 'Fab', 'Gib', 'Hob', 'Job', 'Kob', 'Lob',
  'Mob', 'Nob', 'Pob', 'Rob', 'Sob', 'Tob', 'Vob', 'Alf', 'Bud', 'Curt',
  'Dick', 'Dirk', 'Doug', 'Duff', 'Duke', 'Earl', 'Fred', 'Gene', 'Hank', 'Herb',
  // Unusual/Exotic
  'Absalom', 'Bartholomew', 'Chrysostom', 'Dionysius', 'Epaphroditus', 'Fortunatus', 'Gelasius', 'Heliodorus', 'Irenaeus', 'Januarius',
  'Kallistos', 'Leontios', 'Makarios', 'Nikodemos', 'Onesiphorus', 'Polykarpos', 'Quadratus', 'Romanos', 'Sophronios', 'Theophilos',
  'Auxentios', 'Blasios', 'Christophoros', 'Dositheos', 'Eustathios', 'Philotheos', 'Gennadios', 'Hypatios', 'Ignatios', 'Kassianos',
  'Leontius', 'Methodios', 'Nektarios', 'Onesimos', 'Paphnutios', 'Sabbatios', 'Theodosios', 'Zenobios', 'Anastasios', 'Basileios',
  'Dionysios', 'Evagrios', 'Gregorios', 'Hieronymos', 'Isidoros', 'Kosmas', 'Lazaros', 'Markianos', 'Nephon', 'Palladios',
  // Additional Medieval
  'Adelard', 'Berengar', 'Clovis', 'Dagobert', 'Einhard', 'Folcard', 'Gerbert', 'Hardwin', 'Ingelram', 'Jocelin',
  'Karlmann', 'Lothar', 'Merovech', 'Notker', 'Odo', 'Pepin', 'Radulf', 'Sigibert', 'Tancred', 'Wido',
  'Adelbert', 'Boso', 'Childeric', 'Drogo', 'Ermengard', 'Fulk', 'Gerold', 'Hincmar', 'Ingomer', 'Judith',
  'Liutprand', 'Manasses', 'Nithard', 'Otger', 'Pippin', 'Ratold', 'Sedulius', 'Theodulf', 'Waldrada', 'Arnulf',
  'Bruno', 'Carloman', 'Dado', 'Ebalus', 'Fromond', 'Gauzlin', 'Heribald', 'Immo', 'Josbert', 'Kuno',
  // More Common Names
  'Alan', 'Blake', 'Craig', 'Dean', 'Evan', 'Finn', 'Grant', 'Heath', 'Ian', 'Joel',
  'Kirk', 'Lance', 'Mark', 'Noel', 'Owen', 'Paul', 'Reid', 'Sean', 'Todd', 'Wade',
  'Wyatt', 'Zane', 'Adam', 'Brent', 'Clark', 'Dane', 'Ellis', 'Ford', 'Grant', 'Hayes',
  'Jace', 'Kane', 'Lane', 'Nash', 'Pax', 'Rhys', 'Shane', 'Troy', 'Vance', 'West',
  'Ace', 'Blaine', 'Chase', 'Dex', 'Gage', 'Jett', 'Knox', 'Mace', 'Rex', 'Trace',
  // Additional Fantasy
  'Alderon', 'Brindor', 'Caelan', 'Dravos', 'Eldarion', 'Faelon', 'Galdric', 'Haemon', 'Ildarion', 'Jorath',
  'Kaelen', 'Lhoris', 'Maelorn', 'Naemon', 'Oronir', 'Phareon', 'Quinthar', 'Raelon', 'Saelar', 'Thaeon',
  'Uldric', 'Vaelorn', 'Wyndham', 'Xalvador', 'Yroden', 'Zephros', 'Aerion', 'Baelon', 'Caelum', 'Daeron',
  'Eldric', 'Faeron', 'Galden', 'Haldor', 'Iorath', 'Jaelon', 'Keldorn', 'Lorien', 'Maelor', 'Naeris',
  'Orlan', 'Pyris', 'Quorin', 'Raelor', 'Seldor', 'Thaelon', 'Uvorn', 'Valdris', 'Wynric', 'Xandros',
  // More Names to reach 1000+
  'Abner', 'Basil', 'Cyrus', 'Dorian', 'Eliot', 'Fitz', 'Godfrey', 'Hadley', 'Irving', 'Jarrod',
  'Kemp', 'Lionel', 'Murray', 'Newton', 'Orville', 'Preston', 'Quinton', 'Ramsey', 'Spencer', 'Trent',
  'Urban', 'Vernon', 'Wendell', 'Yale', 'Zander', 'Abbott', 'Barton', 'Clifford', 'Dalton', 'Elmer',
  'Foster', 'Gilbert', 'Hollis', 'Irwin', 'Jasper', 'Kelvin', 'Luther', 'Milton', 'Norton', 'Osbert',
  'Porter', 'Quigley', 'Rodger', 'Sidney', 'Tilden', 'Ulmer', 'Virgil', 'Wilbur', 'Yancy', 'Zebedee',
  'Addison', 'Bradford', 'Carlton', 'Dawson', 'Emerson', 'Franklin', 'Grayson', 'Hamilton', 'Jackson', 'Jefferson',
  'Kingston', 'Lincoln', 'Madison', 'Nelson', 'Oakley', 'Paxton', 'Quincy', 'Remington', 'Sutton', 'Trenton',
  'Upton', 'Weston', 'Dalton', 'Easton', 'Fulton', 'Gideon', 'Hampton', 'Jameson', 'Kellan', 'Lawton',
  'Marshall', 'Nolan', 'Orson', 'Paxton', 'Quade', 'Rowan', 'Saxon', 'Theron', 'Uland', 'Vaughn',
  'Watson', 'Xander', 'Yates', 'Zephyr', 'Alston', 'Benton', 'Colton', 'Dalton', 'Elton', 'Felton',
  'Galton', 'Halton', 'Ilton', 'Jolton', 'Kelton', 'Lanton', 'Malton', 'Nilton', 'Olton', 'Pilton',
  'Quilton', 'Ralton', 'Salton', 'Talton', 'Ulton', 'Valton', 'Walton', 'Yalton', 'Zalton', 'Ashton',
  'Boston', 'Clinton', 'Denton', 'Everton', 'Fenton', 'Grafton', 'Horton', 'Ireton', 'Jordon', 'Kenton',
  'Langton', 'Morton', 'Newton', 'Orton', 'Patton', 'Quinton', 'Rowton', 'Sexton', 'Thornton', 'Upton',
  'Vinton', 'Wharton', 'Yarton', 'Zayton', 'Albion', 'Byron', 'Corbin', 'Dustin', 'Emory', 'Florian',
  'Garrison', 'Haddon', 'Ignatius', 'Judson', 'Kelsey', 'Langley', 'Marsden', 'Neville', 'Ogden', 'Prescott',
]

export const HUMAN_FEMALE_NAMES = [
  // Classic Medieval
  'Adelaide', 'Beatrice', 'Catherine', 'Diana', 'Eleanor', 'Fiona', 'Gwendolyn', 'Helena', 'Isabelle', 'Josephine',
  'Katherine', 'Lydia', 'Margaret', 'Natalie', 'Ophelia', 'Penelope', 'Quintessa', 'Rosalind', 'Sophia', 'Theodora',
  'Ursula', 'Victoria', 'Winifred', 'Xenia', 'Yvonne', 'Zelda', 'Amelia', 'Bridget', 'Cordelia', 'Dorothea',
  'Emmeline', 'Florence', 'Genevieve', 'Harriet', 'Imogen', 'Juliet', 'Katrina', 'Lillian', 'Miriam', 'Nora',
  'Octavia', 'Priscilla', 'Rowena', 'Sabrina', 'Tabitha', 'Vivienne', 'Willa', 'Aurora', 'Briana', 'Celeste',
  'Daphne', 'Elena', 'Freya', 'Gloria', 'Hannah', 'Iris', 'Jasmine', 'Kira', 'Luna', 'Maya',
  'Nina', 'Olivia', 'Petra', 'Rachel', 'Sarah', 'Tessa', 'Vera', 'Willow', 'Aria', 'Bianca',
  'Clara', 'Dahlia', 'Eva', 'Faith', 'Grace', 'Hope', 'Ivy', 'Joy', 'Lily', 'Mira',
  'Nadia', 'Opal', 'Pearl', 'Ruby', 'Stella', 'Terra', 'Violet', 'Alina', 'Brynn', 'Cora',
  'Elara', 'Gemma', 'Hazel', 'Isla', 'Jade', 'Kyla', 'Lena', 'Mila', 'Nova', 'Piper',
  // Fantasy Variants
  'Alarice', 'Branwen', 'Coraline', 'Delphine', 'Elspeth', 'Fern', 'Giselle', 'Hollis', 'Isolde', 'Juniper',
  'Kestrel', 'Lorelei', 'Meadow', 'Nimue', 'Ondine', 'Phaedra', 'Quincy', 'Rhiannon', 'Seraphina', 'Tamsin',
  'Una', 'Vesper', 'Winona', 'Xiomara', 'Yseult', 'Zinnia', 'Astrid', 'Brielle', 'Cassandra', 'Deirdre',
  'Elowen', 'Fiora', 'Guinevere', 'Hermione', 'Iolanthe', 'Jessamine', 'Kalista', 'Lavinia', 'Morgana', 'Nerissa',
  'Oleander', 'Persephone', 'Querida', 'Ravenna', 'Sybilla', 'Tempest', 'Undine', 'Valeria', 'Waverly', 'Xanthe',
  // Noble Names
  'Adelina', 'Berengaria', 'Constance', 'Desdemona', 'Euphemia', 'Frederica', 'Gwendolen', 'Henrietta', 'Ingrid', 'Jacqueline',
  'Katarina', 'Leonora', 'Mathilda', 'Nicolette', 'Ottilie', 'Perpetua', 'Queenilda', 'Rosemonde', 'Scholastica', 'Theodosia',
  'Ursuline', 'Valentina', 'Wilhelmina', 'Ximena', 'Yolanda', 'Zenobia', 'Anastasia', 'Benedikta', 'Clotilde', 'Dagmar',
  'Ermengarde', 'Felicitas', 'Gertrude', 'Hildegard', 'Irmentrude', 'Jacoba', 'Kunigunde', 'Liutgard', 'Mechthild', 'Notburga',
  'Oda', 'Petronilla', 'Richardis', 'Sigrid', 'Thekla', 'Uta', 'Vreneli', 'Walburga', 'Ymma', 'Zofia',
  // Common Folk Names
  'Agnes', 'Bess', 'Cicely', 'Dorcas', 'Edith', 'Flora', 'Greta', 'Hilda', 'Ida', 'Joan',
  'Kate', 'Lettie', 'Maud', 'Nell', 'Oona', 'Peg', 'Rosa', 'Susan', 'Tilly', 'Una',
  'Vera', 'Winnie', 'Nan', 'Alice', 'Betty', 'Celia', 'Daisy', 'Elsie', 'Fanny', 'Gwen',
  'Hatty', 'Ina', 'Jennie', 'Kitty', 'Lottie', 'Maggie', 'Nettie', 'Olga', 'Polly', 'Queenie',
  'Ruth', 'Sally', 'Tessie', 'Ursa', 'Vesta', 'Wanda', 'Xana', 'Yetta', 'Zora', 'Annie',
  // Regional Variants - Northern
  'Astrid', 'Birgit', 'Dagny', 'Eira', 'Freydis', 'Gunnhild', 'Helga', 'Ingeborg', 'Jorunn', 'Kari',
  'Liv', 'Magnhild', 'Nanna', 'Oddny', 'Ragnhild', 'Sigrun', 'Thora', 'Ulfhild', 'Vigdis', 'Yngvild',
  'Asa', 'Bodil', 'Dagmar', 'Embla', 'Freja', 'Gudrun', 'Haldis', 'Idun', 'Jofrid', 'Kolbrun',
  'Ljuva', 'Mathilda', 'Norna', 'Olava', 'Runa', 'Sif', 'Thyra', 'Ulrika', 'Valdis', 'Ylva',
  'Alfhild', 'Brynhild', 'Disa', 'Estrid', 'Gerd', 'Hallveig', 'Inga', 'Jutta', 'Kata', 'Lagertha',
  // Regional Variants - Southern/Mediterranean
  'Alessandra', 'Benedetta', 'Carlotta', 'Daniela', 'Elisabetta', 'Francesca', 'Giovanna', 'Helena', 'Isabella', 'Julia',
  'Lucia', 'Maria', 'Nicoletta', 'Ornella', 'Paola', 'Raffaella', 'Silvana', 'Teodora', 'Umberta', 'Violetta',
  'Adelina', 'Bianca', 'Carmela', 'Donatella', 'Emilia', 'Fiammetta', 'Grazia', 'Ilaria', 'Julietta', 'Katia',
  'Lorenza', 'Michela', 'Natalia', 'Oriana', 'Patrizia', 'Regina', 'Stefania', 'Tiziana', 'Valentina', 'Ximena',
  'Alessia', 'Beatriz', 'Chiara', 'Dolores', 'Esperanza', 'Fernanda', 'Gabriella', 'Ines', 'Josefa', 'Leonor',
  // Regional Variants - Eastern
  'Aleksandra', 'Bronislava', 'Czeslawa', 'Danuta', 'Elzbieta', 'Franciszka', 'Grazyna', 'Halina', 'Irena', 'Jadwiga',
  'Katarzyna', 'Ludmila', 'Malgorzata', 'Natasha', 'Olga', 'Paulina', 'Renata', 'Stanislawa', 'Tatiana', 'Urszula',
  'Wanda', 'Zofia', 'Anastazja', 'Bogumila', 'Celestyna', 'Dorota', 'Ewa', 'Felicja', 'Genowefa', 'Helena',
  'Izabela', 'Jolanta', 'Krystyna', 'Lidia', 'Marianna', 'Natalia', 'Otylia', 'Patrycja', 'Rozalia', 'Stefania',
  'Teresa', 'Ursula', 'Weronika', 'Ksenia', 'Zuzanna', 'Agnieszka', 'Barbara', 'Cecylia', 'Diana', 'Edyta',
  // Regional Variants - Western/Celtic
  'Aisling', 'Brigid', 'Caoimhe', 'Deirdre', 'Eithne', 'Fionnuala', 'Grainne', 'Honora', 'Iona', 'Keira',
  'Liadain', 'Maeve', 'Niamh', 'Orlaith', 'Roisin', 'Saoirse', 'Tara', 'Aoife', 'Blaithin', 'Ciara',
  'Dervla', 'Eileen', 'Finola', 'Gormlaith', 'Ide', 'Keelin', 'Laoise', 'Muireann', 'Neasa', 'Oonagh',
  'Padraigín', 'Ríona', 'Siobhan', 'Treasa', 'Ailbhe', 'Bedelia', 'Clodagh', 'Dairine', 'Emer', 'Fidelma',
  'Gobnat', 'Ide', 'Juno', 'Kerry', 'Liadan', 'Mor', 'Nuala', 'Orna', 'Ríonach', 'Sorcha',
  // Merchant/Trade Names
  'Aldith', 'Basilia', 'Clarice', 'Dionisia', 'Egelina', 'Felice', 'Gisela', 'Hersilia', 'Idonea', 'Juliana',
  'Kundry', 'Leticia', 'Millicent', 'Nichola', 'Osanna', 'Patronella', 'Ricarda', 'Sibilla', 'Thomasina', 'Urith',
  'Venetia', 'Wilmot', 'Yolande', 'Zenith', 'Aveline', 'Benedicta', 'Cristiana', 'Denise', 'Emelina', 'Felicia',
  'Gunnora', 'Helewise', 'Idonia', 'Jocosa', 'Katerine', 'Luciana', 'Margery', 'Nicholaa', 'Oriel', 'Philippa',
  'Roesia', 'Sanchia', 'Tiffany', 'Urraca', 'Viridis', 'Wynefreda', 'Xpiana', 'Ysabel', 'Zillah', 'Aldusa',
  // Nature-Inspired
  'Amber', 'Brook', 'Coral', 'Dawn', 'Ember', 'Fern', 'Ginger', 'Holly', 'Ivy', 'Jasmine',
  'Laurel', 'Meadow', 'Olive', 'Poppy', 'Rain', 'Summer', 'Terra', 'Vale', 'Willow', 'Yara',
  'Alder', 'Blossom', 'Clover', 'Dew', 'Echo', 'Flora', 'Gale', 'Heather', 'Iris', 'Juniper',
  'Kelp', 'Lotus', 'Moss', 'Nectar', 'Orchid', 'Petal', 'Quill', 'Rose', 'Sage', 'Thistle',
  'Umber', 'Violet', 'Wren', 'Yarrow', 'Zinnia', 'Autumn', 'Berry', 'Cedar', 'Delta', 'Elm',
  // Virtue Names
  'Amity', 'Bliss', 'Charity', 'Divine', 'Esperance', 'Felicity', 'Grace', 'Honor', 'Innocence', 'Justice',
  'Kindred', 'Liberty', 'Mercy', 'Noble', 'Patience', 'Quiet', 'Reverence', 'Serenity', 'Truth', 'Unity',
  'Verity', 'Wisdom', 'Zeal', 'Ardent', 'Blessing', 'Clarity', 'Devotion', 'Earnest', 'Faith', 'Glory',
  'Harmony', 'Integrity', 'Joy', 'Kindness', 'Love', 'Modesty', 'Nobility', 'Obedience', 'Prudence', 'Radiance',
  'Spirit', 'Temperance', 'Valor', 'Wonder', 'Allegra', 'Bonita', 'Caritas', 'Decima', 'Elvira', 'Fides',
  // Compound/Old English
  'Aelfgifu', 'Beornwyn', 'Cwenburh', 'Dunwyn', 'Eadburh', 'Frithswith', 'Godgifu', 'Hereswith', 'Ingegyth', 'Judith',
  'Kyneburh', 'Leofrun', 'Mildgyth', 'Nothgyth', 'Osgyth', 'Pleggyth', 'Raedwyn', 'Saeswith', 'Torhtgyth', 'Wulfrun',
  'Aethelflaed', 'Burgwynn', 'Ceolwyn', 'Deorwynn', 'Ealdgyth', 'Forthwyn', 'Goldwynn', 'Herewynn', 'Irminwynn', 'Kenswith',
  'Lindwynn', 'Maelwynn', 'Northwynn', 'Oswynn', 'Plegwynn', 'Redwynn', 'Swithhild', 'Thryth', 'Wulfhild', 'Aelfwynn',
  'Beornhild', 'Cynehild', 'Denewulf', 'Ecgwynn', 'Frithuhild', 'Goldrun', 'Hildegyth', 'Ingeld', 'Kyneswith', 'Leofhild',
  // Short/Simple Names
  'Ada', 'Bea', 'Cass', 'Di', 'Elle', 'Fay', 'Gwen', 'Hal', 'Jan', 'Kay',
  'Lee', 'Mae', 'Nan', 'Pia', 'Quinn', 'Rae', 'Sue', 'Tia', 'Val', 'Wynn',
  'Zoe', 'Ann', 'Belle', 'Cleo', 'Dot', 'Ella', 'Flo', 'Gail', 'Hope', 'Iris',
  'Jane', 'Kim', 'Lou', 'Meg', 'Nell', 'Pat', 'Roz', 'Sal', 'Tess', 'Viv',
  'Wendy', 'Amy', 'Beth', 'Cara', 'Dina', 'Edie', 'Fern', 'Gina', 'Heidi', 'Inez',
  // Unusual/Exotic
  'Aphrodite', 'Berenice', 'Calliope', 'Demeter', 'Electra', 'Philomena', 'Galatea', 'Hecate', 'Iphigenia', 'Jocasta',
  'Kallisto', 'Lysistrata', 'Medea', 'Nyx', 'Olympia', 'Pandora', 'Rhea', 'Selene', 'Thalia', 'Urania',
  'Xantippe', 'Zenobia', 'Ariadne', 'Cassiopeia', 'Danae', 'Eurydice', 'Phaedra', 'Harmonia', 'Io', 'Leda',
  'Mnemosyne', 'Nausicaa', 'Penelope', 'Psyche', 'Sappho', 'Thetis', 'Alcestis', 'Antigone', 'Clytemnestra', 'Dido',
  'Andromeda', 'Briseis', 'Circe', 'Dione', 'Echo', 'Phoebe', 'Gaia', 'Hera', 'Iris', 'Kleopatra',
  // Additional Medieval
  'Adelheid', 'Bertha', 'Cunegunda', 'Drusilla', 'Ermentrude', 'Fastrada', 'Gerberga', 'Herleva', 'Irmengard', 'Judith',
  'Kriemhild', 'Lotaria', 'Matilda', 'Nithard', 'Oda', 'Plectrude', 'Radegund', 'Sunniva', 'Theutberga', 'Wulfhilda',
  'Adeliza', 'Blanche', 'Clemence', 'Denise', 'Eustacia', 'Floria', 'Gundred', 'Hawise', 'Ida', 'Jehanne',
  'Kinborough', 'Letice', 'Mabilia', 'Nicola', 'Oriel', 'Petronilla', 'Roese', 'Sybil', 'Thomasia', 'Urraca',
  'Viridiana', 'Winnoc', 'Ysmaine', 'Zenone', 'Adelais', 'Beatrix', 'Claremonde', 'Dionise', 'Ermengard', 'Foscarina',
  // More Common Names
  'Abigail', 'Brooke', 'Caitlin', 'Dana', 'Emma', 'Frances', 'Georgia', 'Helen', 'Isabel', 'Jessica',
  'Karen', 'Lauren', 'Michelle', 'Nicole', 'Paige', 'Rebecca', 'Samantha', 'Taylor', 'Victoria', 'Whitney',
  'Alexis', 'Brianna', 'Courtney', 'Danielle', 'Emily', 'Gabrielle', 'Heather', 'Jennifer', 'Kimberly', 'Lindsay',
  'Madison', 'Natasha', 'Olivia', 'Patricia', 'Rachel', 'Stephanie', 'Tiffany', 'Vanessa', 'Zara', 'Andrea',
  'Brittany', 'Christina', 'Deanna', 'Elizabeth', 'Felicia', 'Gretchen', 'Hayley', 'Jacqueline', 'Kristen', 'Laura',
  // Additional Fantasy
  'Aelindra', 'Brindara', 'Caelwyn', 'Dravenna', 'Elarion', 'Faelora', 'Galdria', 'Haemona', 'Ildaria', 'Joratha',
  'Kaelindra', 'Lhorien', 'Maeloria', 'Naemona', 'Oronira', 'Phaeona', 'Quinthara', 'Raelona', 'Saelara', 'Thaelora',
  'Uldrica', 'Vaeloria', 'Wyndara', 'Xalvina', 'Yrodena', 'Zephira', 'Aeriona', 'Baelora', 'Caeluma', 'Daerona',
  'Eldrica', 'Faerona', 'Galdena', 'Haldora', 'Ioratha', 'Jaelona', 'Keldora', 'Lorienia', 'Maelora', 'Naerisa',
  'Orlana', 'Pyria', 'Quorina', 'Raelora', 'Seldora', 'Thaelona', 'Uvorna', 'Valdria', 'Wynrica', 'Xandrosa',
  // More Names to reach 1000+
  'Agatha', 'Bernice', 'Claudia', 'Delia', 'Evelyn', 'Frances', 'Geraldine', 'Harriet', 'Irma', 'Janet',
  'Kathleen', 'Lorraine', 'Marian', 'Norma', 'Opal', 'Pauline', 'Rita', 'Sylvia', 'Thelma', 'Velma',
  'Winifred', 'Yvette', 'Zelma', 'Adelaide', 'Bernadette', 'Cecilia', 'Dolores', 'Estelle', 'Francine', 'Gladys',
  'Henrietta', 'Isadora', 'Juanita', 'Kathryn', 'Lilian', 'Marcella', 'Noreen', 'Ophelia', 'Priscilla', 'Rosemary',
  'Shirley', 'Theresa', 'Valerie', 'Wanda', 'Yolanda', 'Zenaida', 'Allison', 'Beverly', 'Carolyn', 'Dorothy',
  'Elaine', 'Faye', 'Gertrude', 'Helene', 'Ingrid', 'Janice', 'Kristine', 'Lucille', 'Marilyn', 'Nadine',
  'Odette', 'Paulette', 'Rosalyn', 'Sandra', 'Trudy', 'Valeria', 'Winona', 'Yvonne', 'Zelda', 'Antonia',
  'Bonnie', 'Carmen', 'Denise', 'Eleanor', 'Florence', 'Glenda', 'Helga', 'Ilene', 'Joanne', 'Kristina',
  'Lenore', 'Marjorie', 'Nanette', 'Olga', 'Patricia', 'Roberta', 'Sheila', 'Tamara', 'Ursula', 'Veronica',
  'Wilma', 'Ximena', 'Yesenia', 'Zara', 'Audrey', 'Beatrix', 'Colette', 'Daphne', 'Estella', 'Fern',
  'Geneva', 'Helena', 'Imogene', 'Josepha', 'Katya', 'Leona', 'Meredith', 'Nadia', 'Odessa', 'Petra',
  'Ramona', 'Selma', 'Tatyana', 'Una', 'Viviana', 'Wendy', 'Xena', 'Yuki', 'Zelda', 'Althea',
  'Bridgette', 'Constance', 'Davina', 'Edwina', 'Fernanda', 'Gilda', 'Honora', 'Ileana', 'Jovana', 'Kendra',
  'Leila', 'Marina', 'Nola', 'Olena', 'Paloma', 'Rhoda', 'Serena', 'Thea', 'Ulrika', 'Vivien',
  'Willa', 'Xanthe', 'Yasmin', 'Zora', 'Adriana', 'Belinda', 'Carlotta', 'Dina', 'Eliza', 'Frederica',
  'Giulia', 'Hortense', 'Imelda', 'Jovita', 'Karla', 'Liana', 'Marisol', 'Natalya', 'Olympia', 'Pilar',
]
